### ISSUE TITLE
Requirements File Missing!

### ISSUE THREAD

**Issue by kinghadra** [aqeelanwar/AnalyzeTheChat#1]
Kindly add the requirements.txt file!

**Comment by aqeelanwar** [comment]
Added.

**Comment by kinghadra** [comment]
Hey Aqeel!
I am a Biochem student (I stalked you online to find that you are from Pak
lmao, I am India btw) and I am not that good with programming. But I
git-cloned your program and it did not work for me. There was decoder
error, so changed the chat txt file to ANSI (original type was utf8) and it
also had some kind of problem/error. I ended up using someone else's
software for analysing my group chat (have you tested the code yourself?),
I hope you'll fix the code. Do let me know when you change it, I'll try it
out.

Chao!

**Comment by kinghadra** [comment]
*I am from India
*so I changed
